server:
    port: ${PORT:8080}
 
spring:
    profiles:
        active: prod
    data:
        mongodb:
            uri: ${H_MONGODB}

logging:
    level:
        ROOT: INFO
        org.springframework.web: INFO
        com.github.rsallar.cineapi: DEBUG