server:
    port: 8080
 
spring:
    profiles:
        active: dev
    data:
        mongodb:
            uri: ${H_MONGODB}

logging:
    level:
        ROOT: DEBUG
        org.springframework.web: INFO
        com.github.rsallar.cineapi: DEBUG