server:
    port: ${PORT:8080}
 
spring:
    profiles:
        active: prod
    data:
        mongodb:
            uri: ${H_MONGODB}
    cache:
        caffeine:
            spec:  maximumSize=200,refreshAfterWrite=24h
