server:
    port: 8080
 
spring:
    profiles: dev

    data:
        mongodb:
            host: localhost
            port: 27017
            database: devBookshelfDB
logging:
    level:
        org.springframework.web: DEBUG
        com.github.rsallar.cineapi: DEBUG
        org.springframework.cache: TRACE
        
